# Enhanced Fusion Configuration Example

fusion:
  # Basic settings (backward compatible)
  bm25_weight: 0.45
  
  # Enhanced fusion settings
  strategy: "rrf"  # Options: "rrf", "weighted_linear", "learned_weights"
  normalization: "none"  # Options: "none", "min_max", "z_score", "rank_based"
  rrf_constant: 60.0
  
  # Adaptive weighting settings
  adaptive_weighting: true
  query_type_weights:
    natural: 0.35    # Favor semantic for natural language
    code: 0.65       # Favor lexical for code queries
    symbol: 0.75     # Heavily favor lexical for symbols
    file: 0.55       # Slightly favor lexical for file queries
    import: 0.70     # Favor lexical for import queries
    config: 0.80     # Heavily favor lexical for config queries
  
  # Boost factors
  exact_match_boost: 1.5
  symbol_match_boost: 1.3
  file_type_boost: 1.2
  recency_boost: 1.1
  
  # Score thresholds
  min_lexical_score: 0.001
  min_semantic_score: 0.05
  
  # Analytics and debugging
  enable_analytics: true
  debug_scoring: false